# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - LineBotTg

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_70da19aada2d413ebc7ae794225a3d81 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0f9579accc2e42fca39286147f45654b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_70da19aada2d413ebc7ae794225a3d81 }}/linebottg:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'LineBotTg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f80a183283654c5c8d77f0dd29a935e8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_70da19aada2d413ebc7ae794225a3d81 }}/linebottg:${{ github.sha }}'